apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "discogs-server.fullname" . }}-pv
  labels:
    app.kubernetes.io/name: {{ include "discogs-server.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistence.storageClass }}
  hostPath:
    path: /mnt/data
